version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=DB
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - database

  frontend:
    image: kems12/frontend:latest
    container_name: frontend-container
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
    external: false
