version: '3.8'

services:
  database:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABSE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    image: kesm12/backend:latest
    privileged: true
    pid: host
    container_name: backend_container
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=Proyecto1
    ports:
      - '3000:3000'
    volumes:
     - type: bind
       source: /proc
       target: /proc
    restart: always
    depends_on:
      - database
    links:
      - database

  frontend:
    image: kesm12/frontend:latest
    container_name: front_container
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
    links:
      - backend

volumes:
  mongo-data:
    external: false

