version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: MongoDB
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"  # Asegúrate de exponer el puerto si tu backend lo necesita

volumes:
  mongo-data: