version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    image: kesm12/backend:latest
    container_name: backend-container
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=DB
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: /proc
        target: /proc
    restart: always
    depends_on:
      - database

  frontend:
    image: kems12/frontend:latest
    container_name: frontend-container
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend

volumes:
  mongo-data:
    external: false

# version: '3'

# services:
#   database:
#     image: mongo
#     container_name: mongo-container
#     restart: always
#     environment:
#       - MONGO_INITDB_DATABSE=DB
#     volumes:
#       - mongo-data:/data/db
#     ports:
#       - '27017:27017'

#   backend:
#     image: kesm12/backend:latest
#     privileged: true
#     pid: host
#     container_name: backend_container
#     environment:
#       - DB_HOST=database
#       - DB_PORT=27017
#       - DB_NAME=DB
#     ports:
#       - '3000:3000'
#     volumes:
#      - type: bind
#        source: /proc
#        target: /proc
#     restart: always
#     depends_on:
#       - database
#     links:
#       - database

#   frontend:
#     image: kems12/frontend:latest
#     container_name: front_container
#     ports:
#       - '80:80'
#     restart: always
#     depends_on:
#       - backend
#     links:
#       - backend

# volumes:
#   mongo-data:
#     external: false
