FROM golang:alpine

WORKDIR /Go

COPY . .

RUN go mod init Proyecto1
RUN go get github.com/gorilla/mux
RUN go get github.com/gorilla/handlers
RUN go get go.mongodb.org/mongo-driver/mongo
RUN go get go.mongodb.org/mongo-driver/mongo/options


EXPOSE 3000

CMD [ "go", "run", "main.go"]
